apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-db
  {{- with .Values.db.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.db.volumeDb.claimRef.name }}
    claimRef:
      {{- with .Values.db.namespace }}
      namespace: {{ . }}
      {{- end }}
      name: {{ .Values.db.volumeDb.claimRef.name }}
  {{- end }}
  resources:
    requests:
      storage: 50Gi
  {{- with .Values.db.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}