apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-db
  {{- with .Values.db.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  {{- with .Values.db.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}