apiVersion: v1
kind: Service
metadata:
  name: solrinterno
  {{- with .Values.solr.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-solr.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: default
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    servico: solr
  sessionAffinity: None
  type: ClusterIP