apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-solr
  {{- with .Values.solr.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  accessModes:
  - ReadWriteMany
  {{- if .Values.solr.volumeSolr.claimRef.name }}
    claimRef:
      {{- with .Values.solr.namespace }}
      namespace: {{ . }}
      {{- end }}
      name: {{ .Values.solr.volumeSolr.claimRef.name }}
  {{- end }}
  resources:
    requests:
      storage: 50Gi
  {{- with .Values.solr.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}