apiVersion: batch/v1
kind: Job
metadata:
  name: sei-inicializador
  {{- with .Values.app.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  backoffLimit: 2
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: sei-inicializador
        {{- include "sei-app.labels" . | nindent 8 }}
    spec:
      containers:
      - command: [ "/bin/bash", "-c" ]
        args: [ "/automationscripts/dbcreate.sh && /entrypoint-atualizador.sh" ]
        envFrom:
        - configMapRef:
            name: sei-app
        - secretRef:
            name: sei-secret1
        image: processoeletronico/app-ci-php8:latest
        imagePullPolicy: Always
        name: sei-inicializador
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /opt
          name: vol1
        - mountPath: /sei/arquivos_externos_sei/
          name: vol2
        - mountPath: /sei/controlador-instalacoes
          name: vol3
        - mountPath: /automationscripts
          name: verificarfontes
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      volumes:
      - name: verificarfontes
        configMap:
          name: cm-verificarfontes
          defaultMode: 0755
      - name: vol1
        persistentVolumeClaim:
          claimName: vol-sei-fontes
      - name: vol2
        persistentVolumeClaim:
          claimName: vol-sei-arquivosexternos
      - name: vol3
        persistentVolumeClaim:
          claimName: vol-sei-controladorinstalacao
