apiVersion: batch/v1
kind: Job
metadata:
  name: sei-dbcreate
  {{- with .Values.app.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  backoffLimit: 2
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: sei-dbcreate
        {{- include "sei-app.labels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - /automationscripts/dbcreate.sh
        envFrom:
        - configMapRef:
            name: sei-app
        - secretRef:
            name: sei-secret1
        image: processoeletronico/install-apoio:0.0.2
        imagePullPolicy: Always
        name: sei-dbcreatekube
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /automationscripts
          name: dbcreate     
        - mountPath: /sei/controlador-instalacoes
          name: vol3
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dbcreate
        configMap:
          name: cm-dbcreate
          defaultMode: 0755
      - name: vol3
        persistentVolumeClaim:
          claimName: vol-sei-controladorinstalacao
