apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-fontes
  {{- with .Values.app.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  {{- if .Values.app.volumeFontes.claimRef.name }}
    claimRef:
      {{- with .Values.app.namespace }}
      namespace: {{ . }}
      {{- end }}
      name: {{ .Values.app.volumeFontes.claimRef.name }}
  {{- end }}
  resources:
    requests:
      storage: 1Gi
  {{- with .Values.app.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}