apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-arquivosexternos
  {{- with .Values.app.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
{{- if .Values.app.volumeAnexos.claimRef.name }}
  claimRef:
    {{- with .Values.app.namespace }}
    namespace: {{ . }}
    {{- end }}
    name: {{ .Values.app.volumeAnexos.claimRef.name }}
{{- end }}
  resources:
    requests:
      storage: 20Gi
  {{- with .Values.app.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}