apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-sei-arquivosexternos
  {{- with .Values.app.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  {{- with .Values.app.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}