apiVersion: v1
kind: Service
metadata:
  name: dbinterno
  {{- with .Values.db.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-db.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: default
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    servico: db
  sessionAffinity: None
  type: ClusterIP