apiVersion: v1
kind: Service
metadata:
  name: memcachedinterno
  {{- with .Values.memcached.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-memcached.labels" . | nindent 4 }}
spec:
  ports:
  - name: tcp
    port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    servico: memcached
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
  type: ClusterIP