apiVersion: v1
binaryData:
  dbcreate.sh: |-
    {{ .Files.Get "apoio/scripts/verificarfontes.sh" | b64enc }}
kind: ConfigMap
metadata:
  name: cm-verificarfontes
  {{- with .Values.app.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}