apiVersion: v1
kind: Service
metadata:
  name: jodinterno
  {{- with .Values.jod.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-jod.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: default
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    servico: jod
  sessionAffinity: None
  type: ClusterIP