apiVersion: v1
kind: Service
metadata:
  name: memcached
  {{- with .Values.app.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  externalName: memcachedinterno.{{ .Values.app.memcachedcluster }}.svc.cluster.local
  sessionAffinity: None
  type: ExternalName
