apiVersion: v1
kind: Service
metadata:
  name: solr
  {{- with .Values.app.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  externalName: solrinterno.{{ .Values.app.solrcluster }}.svc.cluster.local
  sessionAffinity: None
  type: ExternalName
