#orgao: orgaon
memcached:
    
    namespace: ""
        
    image:
        repository: processoeletronico/memcached
        pullPolicy: IfNotPresent
        tag: ""
    
    nameOverride: ""
    fullnameOverride: ""
