apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dth
    ingress.kubernetes.io/app-root: /sei/
    ingress.kubernetes.io/backend-protocol: HTTPS
    ingress.kubernetes.io/proxy-body-size: 200m
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    {{- if ne .Values.memcached_session "true" }}
    nginx.ingress.kubernetes.io/affinity: cookie
    {{- end }}
    nginx.ingress.kubernetes.io/app-root: /sei/
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    {{- if ne .Values.memcached_session "true" }}
    nginx.ingress.kubernetes.io/session-cookie-name: PIINGRESSAFFINITY
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
  name: ing-sei
  {{- with .Values.app.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.app.host }}
    http:
      paths:
      - backend:
          service:
            name: sei-app
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.app.host }}
    #secretName: tls-sei1