apiVersion: v1
data:
  APP_DB_PORTA: {{ .Values.app.db_porta | b64enc }}
  APP_DB_ROOT_PASSWORD: {{ .Values.app.db_root_password | b64enc }}
  APP_DB_ROOT_USERNAME: {{ .Values.app.db_root_username | b64enc }}
  APP_DB_SEI_BASE: {{ printf "%ssei" .Values.app.orgao | lower | b64enc }}
  APP_DB_SEI_PASSWORD: {{ printf "%susei" .Values.app.orgao | lower | b64enc }}
  APP_DB_SEI_USERNAME: {{ printf "%susei" .Values.app.orgao | lower | b64enc }}
  APP_DB_SIP_BASE: {{ printf "%ssip" .Values.app.orgao | lower | b64enc }}
  APP_DB_SIP_PASSWORD: {{ printf "%susip" .Values.app.orgao | lower | b64enc }}
  APP_DB_SIP_USERNAME: {{ printf "%susip" .Values.app.orgao | lower | b64enc }}
  APP_MAIL_AUTENTICAR: {{ .Values.app.mail_autenticar | b64enc }}
  APP_MAIL_PORTA: {{ .Values.app.mail_porta | b64enc }}
  APP_MAIL_SEGURANCA: {{ .Values.app.mail_seguranca | b64enc }}
  APP_MAIL_SENHA: {{ .Values.app.mail_senha | b64enc }}
  APP_MAIL_USUARIO: {{ .Values.app.mail_usuario | b64enc }}
  APP_SEI_CHAVE_ACESSO: {{ .Values.app.sei_chave_acesso | b64enc }}
  APP_SIP_CHAVE_ACESSO: {{ .Values.app.sip_chave_acesso | b64enc }}
  APP_FONTES_GIT_PRIVKEY_BASE64: {{ .Values.app.fontes_git_privkey | b64enc }}
  GITUSER_REPO_MODULOS: {{ .Values.app.gituser_repo_modulos | b64enc }}
  GITPASS_REPO_MODULOS: {{ .Values.app.gitpass_repo_modulos | b64enc }}
  SOLRADMINUSER: {{ .Values.app.solrAdminUser | b64enc }}
  SOLRADMINPASS: {{ .Values.app.solrAdminPass | b64enc }}
kind: Secret
metadata:
  name: sei-secret1
  {{- with .Values.app.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
type: Opaque