apiVersion: v1
data:
  SOLRADMINUSER: {{ .Values.app.solrAdminUser | b64enc }}
  SOLRADMINPASS: {{ .Values.app.solrAdminPass | b64enc }}
kind: Secret
metadata:
  name: sei-solr-secret1-{{ .Values.app.orgao | lower }}
  {{- with .Values.app.solrcluster }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
type: Opaque