apiVersion: apps/v1
kind: Deployment
metadata:
  name: sei-app-agendador
  {{- with .Values.app.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-app.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      servico: app-agendador
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        servico: app-agendador
        {{- include "sei-app.labels" . | nindent 8 }}
    spec:
      containers:
      - command:
        - /entrypoint-agendador.sh
        envFrom:
        - configMapRef:
            name: sei-app
            optional: false
        - secretRef:
            name: sei-secret1
            optional: false
        image: processoeletronico/app-ci-php8-agendador:latest
        imagePullPolicy: Always
        name: sei-app
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /opt/
          name: vol1
        - mountPath: /sei/arquivos_externos_sei/
          name: vol2
        - mountPath: /sei/controlador-instalacoes
          name: vol3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: vol-sei-fontes
      - name: vol2
        persistentVolumeClaim:
          claimName: vol-sei-arquivosexternos
      - name: vol3
        persistentVolumeClaim:
          claimName: vol-sei-controladorinstalacao