db:
    
    namespace: ""

    # informe a classe do pvc onde sera criado o volume de banco 
    # deve estar pre-instalado no seu kubernetes um provisionador nfs
    # gluster ou outro. No caso do docker-desktop ja existe um provisionador 
    # automatico que cria uma pasta na vm do host ou do linux wsl. Para isso deixe
    # o storageclass vazio
    storage:
        storageClass: ""
    
    image:
        repository: processoeletronico/mariadb10.5-sei50
        pullPolicy: IfNotPresent
        tag: ""
    
    nameOverride: ""
    fullnameOverride: ""