solr:
    
    # namespace onde roda o solr, salvo em alguns casos especificos deixe esse valor em branco e informe o namespace pelo helm
    namespace: ""
    
    # informe a classe do pvc onde sera criado o volume do solr
    # deve estar pre-instalado no seu kubernetes um provisionador nfs
    # gluster ou outro. No caso do docker-desktop ja existe um provisionador 
    # automatico que cria uma pasta na vm do host ou do linux wsl. Para isso deixe
    # o storageclass vazio
    # caso contrario tera q criar o pv manualmente 
    storage:
        #storageclass: nfs-client
        storageclass: ""
        
    image:
        repository: processoeletronico/solr9.6.1
        pullPolicy: IfNotPresent
        tag: ""
    
    nameOverride: ""
    fullnameOverride: ""

    # bind dos volumes kubernetes. Em alguns clusters de kube ao subir o pvc faz-se necessario informar o claimRef
    volumeSolr:
      claimRef:
        name: ""