apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  {{- with .Values.memcached.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "sei-memcached.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      servico: memcached
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        servico: memcached
        {{- include "sei-memcached.labels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.memcached.image.pullPolicy }}
        name: memcached
        stdin: true
        tty: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30